n26/force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Country where the contact&apos;s home is located</description>
    <label>Home country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26/force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

n26/force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>External system unique identifier</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card replacement cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country where the product applies</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Currencies_Fees__c.field-meta.xml
<CustomField>
    <fullName>Currencies_Fees__c</fullName>
    <description>ATM Fee in Other Currencies</description>
    <label>Fee in Other Currencies</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Monthly_cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_cost__c</fullName>
    <description>Monthly cost of the product</description>
    <label>Monthly cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

n26/force-app/main/default/classes/REST_ContactProductSyncronitzationTest.cls
@isTest
public with sharing class REST_ContactProductSyncronitzationTest {

    private static final String CONTACT_IDENTIFIER = 'UWHUDEIhiahiedu';

    @TestSetup
    static void makeData(){
        Product2 newProduct = new Product2();
        newProduct.Name = 'Standard';
        newProduct.Country__c = 'DE';
        newProduct.Currencies_Fees__c = 1.7;
        newProduct.Card_Replacement_Cost__c = 0;
        newProduct.Monthly_cost__c = 0;
        insert newProduct;

        Contact newContact = new Contact();
        newContact.LastName = 'Monzonis';
        newContact.Product__c = newProduct.Id;
        newContact.Home_Country__c = 'DE';
        newContact.UUID__c = CONTACT_IDENTIFIER;
        insert newContact;
    }

    @isTest
    public static void givenValidUUID_whenGetProductInformationIsCall_thenReturnProductInformation(){

        RestRequest request = new RestRequest();
        request.requestURI = '/contact/v0/*';
        request.params.put('UUID', CONTACT_IDENTIFIER);
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        REST_ContactProductSyncronitzation.getProductInformation();
        Test.stopTest();

        REST_ContactProductSyncronitzation.ProductWrapper responseBody = (REST_ContactProductSyncronitzation.ProductWrapper) JSON.deserialize(response.responseBody.toString(), REST_ContactProductSyncronitzation.ProductWrapper.class);

        System.assertEquals(CONTACT_IDENTIFIER, responseBody.contactIdentifier);
        System.assertEquals('Standard', responseBody.productInformation.product);
    }

    @isTest
    public static void givenNonParameter_whenGetProductInformationIsCall_thenReturnError(){
        RestRequest request = new RestRequest();
        request.requestURI = '/contact/v0/*';
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        REST_ContactProductSyncronitzation.getProductInformation();
        Test.stopTest();

        System.assertEquals(400, response.statusCode);
    }

    @isTest
    public static void givenInvalidUUID_whenGetProductInformationIsCall_thenReturnError(){
        RestRequest request = new RestRequest();
        request.requestURI = '/contact/v0/*';
        request.params.put('UUID', 'non-exist');
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        REST_ContactProductSyncronitzation.getProductInformation();
        Test.stopTest();

        System.assertEquals(404, response.statusCode);
    }
}