n26/force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Country where the contact&apos;s home is located</description>
    <label>Home country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26/force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

n26/force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>External system unique identifier</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card replacement cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Currencies_Fees__c.field-meta.xml
<CustomField>
    <fullName>Currencies_Fees__c</fullName>
    <description>ATM Fee in Other Currencies</description>
    <label>Fee in Other Currencies</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Monthly_cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_cost__c</fullName>
    <description>Monthly cost of the product</description>
    <label>Monthly cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

n26/force-app/main/default/classes/ContactSelector.cls
/**
 * ContactSelectorI implementation.
 */
public with sharing class ContactSelector implements ContactSelectorI{
    private static ContactSelectorI instance;

    public static ContactSelectorI getInstance(){
        if(instance == null){
            instance = new ContactSelector();
        }
        return instance;
    }

    public Contact getContactById(Id contactId){
        return [SELECT Product__c, Product__r.Name, 
                        Product__r.Monthly_cost__c, Product__r.Currencies_Fees__c, 
                        Product__r.Card_Replacement_Cost__c, Home_Country__c 
                    FROM Contact WHERE id = :contactId];
    }

    public Contact getContactByExternalID(String UUID){
        return [SELECT UUID__c, Product__c, Product__r.Name, 
                        Product__r.Monthly_cost__c, Product__r.Currencies_Fees__c, 
                        Product__r.Card_Replacement_Cost__c, Home_Country__c 
                    FROM Contact WHERE UUID__c = :UUID];
    }
}