n26/force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

n26/force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>External system unique identifier</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card replacement cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Currencies_Fees__c.field-meta.xml
<CustomField>
    <fullName>Currencies_Fees__c</fullName>
    <description>ATM Fee in Other Currencies</description>
    <label>Fee in Other Currencies</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Monthly_cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_cost__c</fullName>
    <description>Monthly cost of the product</description>
    <label>Monthly cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/classes/REST_ContactProductSyncronitzation.cls
@RestResource(urlMapping='/contact/v0/*')
global without sharing class REST_ContactProductSyncronitzation {
    @TestVisible
    private static final String ERROR_MESSAGE = 'An error occurred while retrieving contact information.';
    @TestVisible
    private static final String ERROR_STATUS = 'Failure';

    @HttpGet
    webservice static void getProductInformation(){

        RestRequest request = RestContext.request;
        String contactIdentifier = request.params.get('UUID');

        RestResponse response = RestContext.response;
        response.addHeader('Content-Type', 'application/json');

        if(contactIdentifier != null &&
            !String.isEmpty(contactIdentifier)){
            try{
                ContactSelectorI contactSelector = ContactSelector.getInstance();
                Contact currentContact = contactSelector.getContactByExternalID(contactIdentifier);
                
                ProductWrapper productList = generateResponse(currentContact);
                response.statusCode = 200;
                response.responseBody = Blob.valueOf(JSON.serialize(productList));
            } catch (QueryException ex){
                response.statusCode = 404;
                response.responseBody = Blob.valueOf(JSON.serialize(new Error(ERROR_STATUS, ERROR_MESSAGE)));                
            }
        } else {
            response.statusCode = 400;
            response.responseBody = Blob.valueOf(JSON.serialize(new Error(ERROR_STATUS, ERROR_MESSAGE)));
        }
    }

    private static ProductWrapper generateResponse(Contact contact){
        ProductWrapper result = new ProductWrapper();
        result.contactIdentifier = contact.UUID__c;

        ProductInformationWrapper piWrapperList = new ProductInformationWrapper(contact.product__r.Name,  
                                                                            contact.product__r.Monthly_cost__c, 
                                                                            contact.product__r.Currencies_Fees__c, 
                                                                            contact.product__r.Card_Replacement_Cost__c);

        result.productInformation = piWrapperList;
        return result;
    }

    public class Error{
        public String status;
        public String message;
        
        public Error(String status, String message){
            this.status = status;
            this.message = message;
        }
    }

    public class ProductWrapper{
        public String contactIdentifier;
        public ProductInformationWrapper productInformation;
    }

    public class ProductInformationWrapper{
        public String product;
        public Decimal monthlyCost;
        public Decimal currencyFees;
        public Decimal cardReplacementCost;

        public ProductInformationWrapper(String product, Decimal monthlyCost, Decimal currencyFees, Decimal cardReplacementCost){
            this.product = product;
            this.monthlyCost = monthlyCost;
            this.currencyFees = currencyFees;
            this.cardReplacementCost = cardReplacementCost;
        }
    }
}