n26/force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

n26/force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>External system unique identifier</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card replacement cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country where the product applies</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Currencies_Fees__c.field-meta.xml
<CustomField>
    <fullName>Currencies_Fees__c</fullName>
    <description>ATM Fee in Other Currencies</description>
    <label>Fee in Other Currencies</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

n26/force-app/main/default/objects/Product2/fields/Monthly_cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_cost__c</fullName>
    <description>Monthly cost of the product</description>
    <label>Monthly cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

n26/force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

n26/force-app/main/default/classes/CaseProductInfoControllerTest.cls
@isTest
private class CaseProductInfoControllerTest {
    
    @TestSetup
    static void setupData() {
        Product2 prod = new Product2(
            Name = 'Standard',
            Monthly_cost__c = 0,
            Currencies_Fees__c = 1.7,
            Card_Replacement_Cost__c = 6,
            Country__c = 'DE',
            IsActive = true
        );
        insert prod;

        Contact conWithProduct = new Contact(
            LastName = 'Monzonis',
            Product__c = prod.Id,
            UUID__c = 'dJHASKDASsASss'
        );

        Contact conWithoutProduct = new Contact(
            LastName = 'Marquez',
            UUID__c = 'DSKaasoaDOooO'
        );
        
        insert new List<Contact> {conWithProduct, conWithoutProduct};

        Case caseWithContact =  new Case(
            Subject = 'Case with contact',
            ContactId = conWithProduct.Id
        );

        Case caseWithOutProduct = new Case(
            Subject = 'Caso without product',
            ContactId = conWithoutProduct.Id
        );

        
        Case caseWithoutContact = new Case(
            Subject = 'Caso without contact'
        );
        
        insert new List<Case> {caseWithContact, caseWithOutProduct, caseWithoutContact};
    }
    
    @IsTest
    static void testCaseWithProduct() {
        Case caseWithProduct = [
            SELECT Id FROM Case WHERE Subject = 'Case with contact' LIMIT 1
        ];

        Test.startTest();
        Product2 result = CaseProductInfoController.getProductInfoFromCase(caseWithProduct.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'El producto no debería ser null.');
        System.assertEquals(0, result.Monthly_cost__c, 'Monthly Cost incorrecto.');
    }

    @IsTest
    static void testCaseWithoutProduct() {
        Case caseWithoutProduct = [
            SELECT Id FROM Case WHERE Subject = 'Caso without product' LIMIT 1
        ];

        Test.startTest();
        Product2 result = CaseProductInfoController.getProductInfoFromCase(caseWithoutProduct.Id);
        Test.stopTest();

        System.assertEquals(null, result, 'Debe devolver null si el contacto no tiene producto.');
    }

    @IsTest
    static void testCaseWithoutContact() {
        Case caseWithoutContact = [
            SELECT Id FROM Case WHERE Subject = 'Caso without contact' LIMIT 1
        ];

        Test.startTest();
        Product2 result = CaseProductInfoController.getProductInfoFromCase(caseWithoutContact.Id);
        Test.stopTest();

        System.assertEquals(null, result, 'Debe devolver null si el caso no tiene contacto.');
    }

    @IsTest
    static void testNullCaseId() {
        Test.startTest();
        Product2 result = CaseProductInfoController.getProductInfoFromCase(null);
        Test.stopTest();

        System.assertEquals(null, result, 'Debe devolver null si caseId es null.');
    }
}